/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package cookbook;

import cookbook.splashscreen.SplashScreen;
import javafx.application.Application;
import javafx.stage.Stage;

public class Cookbook extends Application {
  @Override
  public void start(Stage primaryStage) throws Exception {
      
    // Static reference to DbConnector class - connect to DB.
    DbConnector.connect();

    SplashScreen loginMenu = new SplashScreen();
    loginMenu.start(primaryStage);
  }
}
